name: spydf

services:
  spydf:
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 8765
    ports:
      - "8765:8765"
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
